import type { SiteCopy } from "./copy-types";

export const simplifiedChinese: SiteCopy = {
  nav: {
    browse: "浏览插件",
    build: "开发插件",
    github: "GitHub",
    language: "语言",
  },
  footer: {
    description: "为你的 Belfry 工作区制作和分享开源插件。",
    marketplace: "插件市场",
    contributing: "参与贡献",
    source: "源代码",
  },
  home: {
    eyebrow: "Belfry 插件中心",
    titlePrefix: "让你的工作区",
    titleAccent: "更加强大。",
    description:
      "为 Belfry 提供工具、面板、技能和工作流，让能力始终贴近你的代码和本机。",
    browse: "浏览全部插件",
    build: "开发插件",
    note: "开源包 · 权限透明 · 无需账号",
    previewTitle: "从这些插件开始",
    previewReady: "可安装",
    previewNames: ["Git Lens", "Token 用量分析", "小清新待办"],
    stats: ["目录中的插件", "种查找方式", "可审阅的包源码", "所需云端账号"],
    startKicker: "从这里开始",
    startTitle: "第一次使用就能派上用场。",
    startDescription: "专注而小巧的目录，解决 Agent 只差一个能力的时刻。",
    viewAll: "查看全部插件",
    exploreKicker: "按目的探索",
    exploreTitle: "找到适合你的能力。",
    trustKicker: "为信任而设计",
    trustTitle: "把真正有用的信息放在明面上。",
    trustDescription:
      "每个插件进入工作区之前都可以被检查。它能访问什么，由你决定。",
    trustItems: [
      {
        number: "01 / 源码",
        title: "开放包源码",
        description: "从插件仓库安装前，先阅读 manifest、README 和实际实现。",
      },
      {
        number: "02 / 权限",
        title: "明确的能力边界",
        description:
          "文件、网络、Shell 和 Agent 权限都会在浏览过程中直接展示。",
      },
      {
        number: "03 / 安装",
        title: "简单的包流程",
        description:
          "下载版本化的 .piplug 包，在 Belfry 中安装，然后检查宿主权限提示。",
      },
    ],
    builderKicker: "面向开发者",
    builderTitle: "开发你的工作流所缺少的插件。",
    builderDescription:
      "仓库提供小型示例和实用模板，帮助你从想法开始，完成可安装的插件包。",
    builderButton: "阅读贡献指南",
  },
  categories: {
    all: { label: "全部插件", description: "目录中的全部插件。" },
    productivity: {
      label: "效率工具",
      description: "让工作持续推进的小工具。",
    },
    "developer-tools": {
      label: "开发工具",
      description: "检查、修改和理解你的代码库。",
    },
    community: { label: "社区插件", description: "由 Belfry 社区构建的插件。" },
    official: { label: "官方插件", description: "由仓库维护者提供。" },
    template: { label: "模板", description: "开发自己插件的起点。" },
  },
  marketplace: {
    kicker: "插件市场",
    title: "浏览插件。",
    description: "为本地 Belfry 工作区寻找小而专注的扩展。",
    updated: "目录更新于",
    searchPlaceholder: "按名称、能力或分类搜索……",
    search: "搜索",
    resultOne: "个插件",
    resultMany: "个插件",
    matching: "匹配",
    packageNote: "版本化 .piplug 包",
    emptyTitle: "没有找到插件。",
    emptyDescription: "换个关键词，或清除分类筛选。",
  },
  detail: {
    plugins: "插件",
    official: "官方",
    by: "作者",
    catalogOfficial: "插件目录",
    download: "下载 .piplug",
    copyUrl: "复制包地址",
    copied: "已复制",
    source: "查看源码",
    about: "插件介绍",
    noReadme: "暂时没有 README，请前往源码仓库了解实现细节。",
    facts: "插件信息",
    latestVersion: "最新版本",
    requires: "运行要求",
    packageSize: "包大小",
    published: "发布时间",
    category: "分类",
    permissions: "权限",
    noPermissions: "未声明权限。",
    reviewTitle: "安装前请检查",
    reviewDescription: "该插件请求的能力可能访问你的工作区、网络或外部应用。",
    safetyNotes: "安全说明",
    installTitle: "在 Belfry 中安装",
    installDescription:
      "下载插件包，在“设置 → 插件 → 导入插件”中选择文件并确认权限。",
    downloadPackage: "下载插件包",
  },
  docs: {
    home: "首页",
    kicker: "面向开发者",
    title: "开发插件。",
    description:
      "Belfry 插件是小型、版本化的扩展包，可以为本地工作区增加工具、面板、技能和工作流。",
    quickStart: "快速开始",
    qualityTitle: "什么样的插件更好？",
    qualityItems: [
      "README 清楚说明插件做什么，以及会访问什么。",
      "每个发布版本使用语义化版本号，并附带简短变更记录。",
      "只申请必要权限，并用易懂的语言说明风险。",
      "提供 UI 面板时，同时填写本地化的面板标题。",
    ],
    submitTitle: "提交到插件目录",
    submitDescription:
      "按照仓库中的完整贡献清单操作。合并后，目录和插件包就会对 Belfry 用户开放。",
    readGuide: "阅读 CONTRIBUTING.md",
    localTitle: "本地验证",
    localDescription:
      "在 Belfry 中加载开发插件，确认命令和面板，检查权限行为，然后在提交 PR 前测试打包后的 .piplug 文件。",
    templateTitle: "从模板开始",
    templateDescription:
      "一条命令创建面板、Agent 工具、Skill 包或完整示例，清单自动生成。",
    permissionTitle: "只申请真正需要的权限",
    permissionDescription: "用户会检查插件权限，权限范围应尽可能小。",
    packageTitle: "打包并发布",
    packageDescription: "构建 .piplug 包、重建目录，然后提交 Pull Request。",
    sourceFirst: "插件目录坚持源码优先：安装前先阅读 manifest 和 README。",
  },
};
