export type SiteCopy = {
  nav: { browse: string; build: string; github: string; language: string };
  footer: {
    description: string;
    marketplace: string;
    contributing: string;
    source: string;
  };
  home: {
    eyebrow: string;
    titlePrefix: string;
    titleAccent: string;
    description: string;
    browse: string;
    build: string;
    note: string;
    previewTitle: string;
    previewReady: string;
    previewNames: string[];
    stats: string[];
    startKicker: string;
    startTitle: string;
    startDescription: string;
    viewAll: string;
    exploreKicker: string;
    exploreTitle: string;
    trustKicker: string;
    trustTitle: string;
    trustDescription: string;
    trustItems: Array<{ number: string; title: string; description: string }>;
    builderKicker: string;
    builderTitle: string;
    builderDescription: string;
    builderButton: string;
  };
  categories: Record<string, { label: string; description: string }>;
  marketplace: {
    kicker: string;
    title: string;
    description: string;
    updated: string;
    searchPlaceholder: string;
    search: string;
    resultOne: string;
    resultMany: string;
    matching: string;
    packageNote: string;
    emptyTitle: string;
    emptyDescription: string;
  };
  detail: {
    plugins: string;
    official: string;
    by: string;
    catalogOfficial: string;
    download: string;
    copyUrl: string;
    copied: string;
    source: string;
    about: string;
    noReadme: string;
    facts: string;
    latestVersion: string;
    requires: string;
    packageSize: string;
    published: string;
    category: string;
    permissions: string;
    noPermissions: string;
    reviewTitle: string;
    reviewDescription: string;
    safetyNotes: string;
    installTitle: string;
    installDescription: string;
    downloadPackage: string;
  };
  docs: {
    home: string;
    kicker: string;
    title: string;
    description: string;
    quickStart: string;
    qualityTitle: string;
    qualityItems: string[];
    submitTitle: string;
    submitDescription: string;
    readGuide: string;
    localTitle: string;
    localDescription: string;
    templateTitle: string;
    templateDescription: string;
    permissionTitle: string;
    permissionDescription: string;
    packageTitle: string;
    packageDescription: string;
    sourceFirst: string;
  };
};
